alter table if exists notebooks drop constraint if exists FKk5jweiuqjycrab2dgljlc919i
drop table if exists notebooks cascade
drop table if exists users cascade
create table notebooks (id int8 generated by default as identity, text varchar(255), title varchar(255), user_id int8, primary key (id))
create table users (id int8 generated by default as identity, password varchar(255), username varchar(255), primary key (id))
alter table if exists users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username)
alter table if exists notebooks add constraint FKk5jweiuqjycrab2dgljlc919i foreign key (user_id) references users
